-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "emailId" TEXT NOT NULL,
    "Communication_skills" DOUBLE PRECISION NOT NULL,
    "Openness" DOUBLE PRECISION NOT NULL,
    "Conscientousness" DOUBLE PRECISION NOT NULL,
    "Extraversion" DOUBLE PRECISION NOT NULL,
    "Agreeableness" DOUBLE PRECISION NOT NULL,
    "Emotional_Range" DOUBLE PRECISION NOT NULL,
    "Conversation" DOUBLE PRECISION NOT NULL,
    "Openness_to_Change" DOUBLE PRECISION NOT NULL,
    "Hedonism" DOUBLE PRECISION NOT NULL,
    "Self_enhancement" DOUBLE PRECISION NOT NULL,
    "Self_transcendence" DOUBLE PRECISION NOT NULL,
    "Database_Fundamentals" DOUBLE PRECISION NOT NULL,
    "Computer_Architecture" DOUBLE PRECISION NOT NULL,
    "Distributed_Computing_Systems" DOUBLE PRECISION NOT NULL,
    "Cyber_Security" DOUBLE PRECISION NOT NULL,
    "Networking" DOUBLE PRECISION NOT NULL,
    "Software_Development" DOUBLE PRECISION NOT NULL,
    "Programming_Skills" DOUBLE PRECISION NOT NULL,
    "Project_Management" DOUBLE PRECISION NOT NULL,
    "Computer_Forensics_Fundamentals" DOUBLE PRECISION NOT NULL,
    "Technical_Communication" DOUBLE PRECISION NOT NULL,
    "AI_ML" DOUBLE PRECISION NOT NULL,
    "Software_Engineering" DOUBLE PRECISION NOT NULL,
    "Business_Analysis" DOUBLE PRECISION NOT NULL,
    "Data_Science" DOUBLE PRECISION NOT NULL,
    "Troubleshooting_skills" DOUBLE PRECISION NOT NULL,
    "Graphics_Designing" DOUBLE PRECISION NOT NULL,
    "predictedJob" TEXT NOT NULL,
    "interestedJob" TEXT NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
